use portfolio;

create table users(id int not null auto_increment, 
name varchar(50) not null,
image_path varchar(50) not null,
email varchar(50) not null,
linkedin_profile varchar(255),
primary key(id)
);

insert into users(name, image_path,email,linkedin_profile) values ('Aswin Sankaranarayanan','images/user/aswin.png','aswin.sankaranarayanan@gmail.com','https://www.linkedin.com/in/aswin-sankarananrayanan/');


create table skills(id int not null auto_increment, 
name varchar(50) not null,
description TEXT not null,
logo_path varchar(50) not null,
user_fk int,
primary key(id),
foreign key(user_fk) references users(id)
);

insert into skills(name,description,logo_path,user_fk) values ('Angular','3+ years of experience in Angular 8','images/angular.png',1);
insert into skills(name,description,logo_path,user_fk) values ('Node JS','1 year of experience in creating Chat Bot using Node & Express','images/nodejs.png',1);
insert into skills(name,description,logo_path,user_fk) values ('Java','8 years of experience in Java','images/java.png',1);
insert into skills(name,description,logo_path,user_fk) values ('Spring Boot','3+ years of experience in Spring Boot','images/springboot.png',1);
insert into skills(name,description,logo_path,user_fk) values ('Spring Security','Secure Web Applications using Spring Security,JWT,OAuth2','images/spring-security.png',1);
insert into skills(name,description,logo_path,user_fk) values ('Docker','Exposure to containerization using Docker','images/docker.png',1);
insert into skills(name,description,logo_path,user_fk) values ('Kubernetes','Exposure to Container Orchestration using Kubernetes','images/kubernetes.png',1);
insert into skills(name,description,logo_path,user_fk) values ('GCP','Exposure to Google Cloud Platform','images/gcp.png',1);

create table user_description(id int not null auto_increment, 
description TEXT not null,
user_fk int,
primary key(id),
foreign key(user_fk) references users(id)
);

insert into user_description(description,user_fk) values ('I m a Full Stack Developer with 8 years of experience.',1);
insert into user_description(description,user_fk) values ('Acquired skills in Java, Spring, Spring Boot, Angular & Bootstrap.',1);
insert into user_description(description,user_fk) values ('Exposure to Cloud & Microservices.',1);

create table experiences(id int not null auto_increment, 
company_name varchar(255) not null,
duration varchar(255) not null,
order_number int,
user_fk int,
primary key(id),
foreign key(user_fk) references users(id)
);

insert into experiences(company_name,duration,order_number,user_fk) values ('Hexaware Tecnologies','2014-2018',1,1);
insert into experiences(company_name,duration,order_number,user_fk) values ('Wipro','2018-2021',2,1);
insert into experiences(company_name,duration,order_number,user_fk) values ('Bank of America','2021-present',3,1);

create table projects(id int not null auto_increment, 
project_name varchar(255) not null,
project_description TEXT not null,
experience_fk int,
primary key(id),
foreign key(experience_fk) references experiences(id)
);

insert into projects(project_name,project_description,experience_fk) values('Property Manager','Property Manager is a tool for managing application configurations, copy and compare
configurations between environments. This is a legacy tool built using JSP and it is migrated to Angular & Spring Boot',3);

insert into projects(project_name,project_description,experience_fk) values('E-Signature','Earlier clients used the Sign the Contract PDFs using the Signature Fields generated by a
third-party software DocuSign. In Order to reduce the cost incurred for creating Signature Fields by DocuSign
an In-House Product E Signature was developed to achieve the same functionalities of DocuSign. The
Project E-Signature has various options to create Signature Fields based on user defined co-ordinates,
Labelled Text and supports Drag-Drop of Signature Fields. This tool is built with Angular, PSPDFKIT library & Spring Boot',3);

insert into projects(project_name,project_description,experience_fk) values('Prueba','Prueba is an inhouse product that offers real time enterprise test management solution. With this tool the user uploads their automation test cases, Prueba in turn runs the test cases using selenium under the hood & instantly displays the results of the execution – test information, steps in each test, pass percentage, fail percentage & generate reports. User can view the bugs that are identified & the same can be raised in JIRA via Prueba. The user can also manage the test executions of multiple projects using Prueba.',2);

insert into projects(project_name,project_description,experience_fk) values('Deutsche Leasing',
'Leasing Application for Sparkasse Bank, Germany',
1);

create table project_roles(id int not null auto_increment, 
role_description TEXT not null,
project_fk int,
primary key(id),
foreign key(project_fk) references projects(id)
);

insert into project_roles(role_description,project_fk) values ('Participated in the pre-design sessions along with module lead to understand the requirements and provide design considerations.',1);
insert into project_roles(role_description,project_fk) values ('Migrated the application from the JSP to Single Page Application using Angular, Bootstrap & Spring Boot.',1);
insert into project_roles(role_description,project_fk) values ('Performed root cause analysis',1);

insert into project_roles(role_description,project_fk) values ('Participated in the pre-design sessions along with module lead to understand the requirements and provide design considerations.',3);
insert into project_roles(role_description,project_fk) values ('Estimated the change requests and developed the modules as per the specification.',3);
insert into project_roles(role_description,project_fk) values ('Mentored my juniors.',3);

insert into project_roles(role_description,project_fk) values ('Attended the pre-design sessions along with module lead to understand the requirements and provide design considerations',4);
insert into project_roles(role_description,project_fk) values ('Performed analysis of the changes and developed the modules as per functional specification.',4);
insert into project_roles(role_description,project_fk) values ('Delivered a custom logging framework using MDB to monitor production performance.',4);
